name: Test GSpread Secret
# test junjie : run in local vs code      
on:
  workflow_dispatch:      # so you can trigger it manually
  schedule:
    - cron: "0 * * * *"   # optional: every hour

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    env:
      GSPREAD_API_CREDENTIALS_INFO: ${{ secrets.GSPREAD_API_CREDENTIALS_INFO }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install jupyter nbconvert gspread oauth2client pandas numpy
      
      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute code.ipynb

      - name: Display Output Notebook
        run: |
          jupyter nbconvert --to markdown code.nbconvert.ipynb --stdout
