name: Test GSpread Secret
# test junjie : run in local vs code      
on:
  workflow_dispatch:      # so you can trigger it manually

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    env:
      GSPREAD_API_CREDENTIALS_INFO: ${{ secrets.GSPREAD_API_CREDENTIALS_INFO }}
      GOOGLE_ADS_API_KEY : ${{ secrets.GOOGLE_ADS_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Debug - Check if secret exists
        run: |
          if [ -z "$GSPREAD_API_CREDENTIALS_INFO" ]; then
            echo "Secret is NOT set"
          else
            echo "Secret is set, length: ${#GSPREAD_API_CREDENTIALS_INFO}"
          fi


      - name: Debug - Check if secret exists 2 google ads api key
        run: |
          if [ -z "$GOOGLE_ADS_API_KEY" ]; then
            echo "Secret is NOT set"
          else
            echo "Secret is set, length: ${#GOOGLE_ADS_API_KEY}"
          fi
          
          
      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute code.ipynb

      - name: Display Output Notebook
        run: |
          jupyter nbconvert --to markdown code.nbconvert.ipynb --stdout
